fix centos8 issues and introduce USER_POST_INSTALL_SCRIPT_PATH var
This fixes the centos8 docker service issues and adds a variable
USER_POST_INSTALL_SCRIPT_PATH which can be used to point at a bash
script which will be copied and run in the master and all nodes of the
cluster created.

Signed-off-by: Alexander Trost <galexrt@googlemail.com>

diff --git a/vagrantfiles/centos8/common b/vagrantfiles/centos8/common
--- a/vagrantfiles/centos8/common
+++ b/vagrantfiles/centos8/common
@@ -16,6 +16,13 @@ systemctl stop firewalld || true
 systemctl disable firewalld || true
 systemctl mask firewalld || true
 
+retries=5
+for ((i=1; i<=retries; i++)); do
+    yum update -y && \
+        break
+    [[ $retries -eq i ]] && { echo "Failed to update OS packages after 5 tries"; exit 1; }
+done
+
 if [ -n '#{INSTALL_ADDITIONAL_PACKAGES}' ]; then
     yum clean packages
     retries=5
@@ -33,8 +40,8 @@ set -x
 retries=5
 for ((i=1; i<=retries; i++)); do
     yum install -y yum-utils \
-        device-mapper-persistent-data \
-        lvm2 tc
+        lvm2 iproute-tc
+    yum install -y libseccomp
     yum-config-manager \
         --add-repo \
         https://download.docker.com/linux/centos/docker-ce.repo
diff --git a/vagrantfiles/fedora/common b/vagrantfiles/fedora/common
--- a/vagrantfiles/fedora/common
+++ b/vagrantfiles/fedora/common
@@ -23,6 +23,13 @@ if [ ! -f /usr/sbin/iptables-legacy ]; then
 fi
 update-alternatives --set iptables /usr/sbin/iptables-legacy
 
+retries=5
+for ((i=1; i<=retries; i++)); do
+    dnf update -y && \
+        break
+    [[ $retries -eq i ]] && { echo "Failed to update OS packages after 5 tries"; exit 1; }
+done
+
 if [ -n '#{INSTALL_ADDITIONAL_PACKAGES}' ]; then
     dnf clean packages
     retries=5
