vagrant: added variable to install additional pkgs
Added the environment variable `INSTALL_ADDITIONAL_PACKAGES` to easily
install additional packages into the VMs created.

Signed-off-by: Alexander Trost <galexrt@googlemail.com>

diff --git a/vagrantfiles/ubuntu/common b/vagrantfiles/ubuntu/common
--- a/vagrantfiles/ubuntu/common
+++ b/vagrantfiles/ubuntu/common
@@ -33,6 +33,15 @@ for ((i=1; i<=retries; i++)); do
 
     [[ $retries -eq i ]] && { echo "Failed to install apt-transport-https and other dependenices after 5 tries"; exit 1; }
 done
+
+if [ -n '#{INSTALL_ADDITIONAL_PACKAGES}' ]; then
+    retries=5
+    for ((i=1; i<=retries; i++)); do
+        apt-get install -y #{INSTALL_ADDITIONAL_PACKAGES} && \
+            break
+        [[ $retries -eq i ]] && { echo "Failed to install additional packages (#{INSTALL_ADDITIONAL_PACKAGES}) after 5 tries"; exit 1; }
+    done
+fi
 SCRIPT
 
 $docker_version = '5:18.09.1~3-0~ubuntu-bionic'
