Verify that docker, kubeadm and kubelet are found in PATH
Fixed issues with Ubuntu instal by adding retries around "everything".

diff --git a/vagrantfiles/ubuntu/master b/vagrantfiles/ubuntu/master
--- a/vagrantfiles/ubuntu/master
+++ b/vagrantfiles/ubuntu/master
@@ -1,17 +1,23 @@
 $baseInstallScript = <<SCRIPT
 set -x
-apt-get update
-apt-get install -y apt-transport-https curl software-properties-common ca-certificates
+
+retries=5
+for ((i=0; i<retries; i++)); do
+    apt-get update
+    apt-get -y install apt-transport-https curl software-properties-common ca-certificates && \
+        break
+done
+[[ $retries -eq i ]] && { echo "Failed to install apt-transport-https and other dependenices after 5 tries"; exit 1; }
+
 curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
 add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) \
    stable"
-curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
+curl curl --retry 5 --fail -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
 cat <<EOF > /etc/apt/sources.list.d/kubernetes.list
 deb https://apt.kubernetes.io/ kubernetes-xenial main
 EOF
-apt-get update
 
 if [ -n "#{KUBERNETES_VERSION}" ]; then
     KUBERNETES_PACKAGES="kubelet=#{KUBERNETES_VERSION}#{$kubernetes_pkg_version_suffix} kubeadm=#{KUBERNETES_VERSION}#{$kubernetes_pkg_version_suffix} kubectl=#{KUBERNETES_VERSION}#{$kubernetes_pkg_version_suffix}"
@@ -19,8 +25,16 @@ else
     KUBERNETES_PACKAGES="kubelet kubeadm kubectl"
 fi
 
-apt-get install -y screen telnet docker-ce=#{$docker_version} ${KUBERNETES_PACKAGES}
+retries=5
+for ((i=0; i<retries; i++)); do
+    apt-get update
+    apt-get -y install screen telnet conntrack socat docker-ce=#{$docker_version} ${KUBERNETES_PACKAGES} && \
+        break
+done
+[[ $retries -eq i ]] && { echo "Failed to install docker, kubelet, kubeadm and other dependenices after 5 tries"; exit 1; }
+
 apt-mark hold kubelet kubeadm kubectl
+
 # Increase /run dir as it is/was a problem on Ubuntu 18.04 (at least on bento box image)
 echo 'tmpfs /run tmpfs rw,nosuid,noexec,relatime,size=614460k,mode=755' >> /etc/fstab
 SCRIPT
