vagrantfile: fixed retry loops
Signed-off-by: Alexander Trost <galexrt@googlemail.com>

diff --git a/vagrantfiles/Vagrantfile_vars b/vagrantfiles/Vagrantfile_vars
--- a/vagrantfiles/Vagrantfile_vars
+++ b/vagrantfiles/Vagrantfile_vars
@@ -50,6 +50,10 @@ KUBE_PROXY_IPVS = ENV['KUBE_PROXY_IPVS'] || false
 # Generate new using steps in README
 KUBETOKEN = ENV['KUBETOKEN'] || 'b029ee.968a33e8d8e6bb0d'
 
+if $kubeletExtraArgsFile.nil? || $kubeletExtraArgsFile == ""
+    $kubeletExtraArgsFile = '/etc/sysconfig/kubelet'
+end
+
 # The controller name is different per OS it seems (this is the case for at least Ubuntu right now).
 # For more information, see https://github.com/kusnier/vagrant-persistent-storage/issues/33.
 $storagecontroller = 'k8svmSATAController'
@@ -111,6 +115,22 @@ kubelet --version || { echo "Something wrong with kubelet"; exit 1; }
 
 systemctl enable kubelet
 
+mkdir -p /etc/docker
+cat > /etc/docker/daemon.json <<EOF
+{
+  "exec-opts": ["native.cgroupdriver=systemd"],
+  "log-driver": "json-file",
+  "log-opts": {
+    "max-size": "100m"
+  },
+  "storage-driver": "overlay2",
+  "storage-opts": [
+    "overlay2.override_kernel_check=true"
+  ]
+}
+EOF
+
+mkdir -p /etc/systemd/system/docker.service.d
 SCRIPT
 
 $kubeMasterScript = <<SCRIPT
@@ -119,8 +139,8 @@ set -x
 kubeadm reset -f
 
 retries=5
-for ((i=0; i<retries; i++)); do
-    # For now ignore SystemVerification error
+for ((i=1; i<=retries; i++)); do
+    # For now ignore preflight SystemVerification error
     kubeadm init \
         #{$kubeadm_init_flags} \
         --ignore-preflight-errors=SystemVerification \
@@ -128,23 +148,23 @@ for ((i=0; i<retries; i++)); do
         --pod-network-cidr=#{POD_NW_CIDR} \
         --token "#{KUBETOKEN}" \
         --token-ttl 0 && \
-        break
+            break
+
+    [[ $retries -eq i ]] && { echo "Failed to run kubeadm init after 5 tries"; exit 1; }
     echo "kubeadm join failed, trying again in 3 seconds (try ${i}/${retries})..."
     sleep 3
 done
-[[ $retries -eq i ]] && { echo "Failed to run kubeadm init after 5 tries"; exit 1; }
 
-KUBELET_EXTRA_ARGS_FILE=/etc/sysconfig/kubelet
-if [ -f /etc/default/kubelet ]; then
-    KUBELET_EXTRA_ARGS_FILE=/etc/default/kubelet
+KUBELET_EXTRA_ARGS_FILE="#{$kubeletExtraArgsFile}"
+
+if [ -f "$KUBELET_EXTRA_ARGS_FILE" ]; then
+    if grep -q -- '--node-ip=' "$KUBELET_EXTRA_ARGS_FILE"; then
+        sed -ri -e 's|KUBELET_EXTRA_ARGS=--node-ip=[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+|KUBELET_EXTRA_ARGS=|' "$KUBELET_EXTRA_ARGS_FILE"
+    fi
+    sed -i 's|KUBELET_EXTRA_ARGS=|KUBELET_EXTRA_ARGS=--node-ip=#{NODE_IP} --cni-bin-dir=/opt/cni/bin,/usr/libexec/cni |' "$KUBELET_EXTRA_ARGS_FILE"
 else
-    KUBELET_EXTRA_ARGS_FILE=/etc/sysconfig/kubelet
+    echo "KUBELET_EXTRA_ARGS=--node-ip=#{NODE_IP} " > "$KUBELET_EXTRA_ARGS_FILE"
 fi
-
-if grep -q -- '--node-ip=' "$KUBELET_EXTRA_ARGS_FILE"; then
-    sed -ri -e 's|KUBELET_EXTRA_ARGS=--node-ip=[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+|KUBELET_EXTRA_ARGS=|' "$KUBELET_EXTRA_ARGS_FILE"
-fi
-sed -i 's|KUBELET_EXTRA_ARGS=|KUBELET_EXTRA_ARGS=--node-ip=#{NODE_IP} --cni-bin-dir=/opt/cni/bin,/usr/libexec/cni |' "$KUBELET_EXTRA_ARGS_FILE"
 
 systemctl daemon-reload
 systemctl restart kubelet.service
@@ -185,7 +205,7 @@ set -x
 kubeadm reset -f
 
 retries=5
-for ((i=0; i<retries; i++)); do
+for ((i=1; i<=retries; i++)); do
     # For now ignore SystemVerification error
     kubeadm join \
         #{$kubeadm_join_flags} \
@@ -194,20 +214,22 @@ for ((i=0; i<retries; i++)); do
         --token "#{KUBETOKEN}" \
         "#{MASTER_IP}:6443" && \
         break
+
+    [[ $retries -eq i ]] && { echo "Failed to run kubeadm join after 5 tries"; exit 1; }
     echo "kubeadm join failed, trying again in 3 seconds (try ${i}/${retries})..."
     sleep 3
 done
-[[ $retries -eq i ]] && { echo "Failed to run kubeadm join after 5 tries"; exit 1; }
 
-KUBELET_EXTRA_ARGS_FILE=/etc/sysconfig/kubelet
-if [ ! -f /etc/sysconfig/kubelet ]; then
-    KUBELET_EXTRA_ARGS_FILE=/etc/default/kubelet
-fi
+KUBELET_EXTRA_ARGS_FILE="#{$kubeletExtraArgsFile}"
 
-if grep -q -- '--node-ip=' "$KUBELET_EXTRA_ARGS_FILE"; then
-    sed -ri -e 's/KUBELET_EXTRA_ARGS=--node-ip=[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+/KUBELET_EXTRA_ARGS=/' "$KUBELET_EXTRA_ARGS_FILE"
+if [ -f "$KUBELET_EXTRA_ARGS_FILE" ]; then
+    if grep -q -- '--node-ip=' "$KUBELET_EXTRA_ARGS_FILE"; then
+        sed -ri -e 's|KUBELET_EXTRA_ARGS=--node-ip=[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+|KUBELET_EXTRA_ARGS=|' "$KUBELET_EXTRA_ARGS_FILE"
+    fi
+    sed -i 's|KUBELET_EXTRA_ARGS=|KUBELET_EXTRA_ARGS=--node-ip=#{NODE_IP} --cni-bin-dir=/opt/cni/bin,/usr/libexec/cni |' "$KUBELET_EXTRA_ARGS_FILE"
+else
+    echo "KUBELET_EXTRA_ARGS=--node-ip=#{NODE_IP} " > "$KUBELET_EXTRA_ARGS_FILE"
 fi
-sed -i 's|KUBELET_EXTRA_ARGS=|KUBELET_EXTRA_ARGS=--node-ip=#{NODE_IP} --cni-bin-dir=/opt/cni/bin,/usr/libexec/cni |' "$KUBELET_EXTRA_ARGS_FILE"
 
 systemctl daemon-reload
 systemctl restart kubelet.service
diff --git a/vagrantfiles/fedora/common b/vagrantfiles/fedora/common
--- a/vagrantfiles/fedora/common
+++ b/vagrantfiles/fedora/common
@@ -2,8 +2,16 @@ $box_image = ENV['BOX_IMAGE'] || 'fedora/30-cloud-base'.freeze
 
 # Use iptables-legacy for iptables
 $osPrepareScript = <<SCRIPT
+set -x
+
 if [ ! -f /usr/sbin/iptables-legacy ]; then
-    dnf install -y iptables
+    retries=5
+    for ((i=1; i<=retries; i++)); do
+        dnf install -y iptables && \
+            break
+
+        [[ $retries -eq i ]] && { echo "Failed to install iptables after 5 tries"; exit 1; }
+    done
 fi
 update-alternatives --set iptables /usr/sbin/iptables-legacy
 SCRIPT
@@ -12,13 +20,14 @@ $containerRuntimeInstallScript = <<SCRIPT
 set -x
 
 retries=5
-for ((i=0; i<retries; i++)); do
+for ((i=1; i<retries; i++)); do
     dnf -y install dnf-plugins-core
     dnf config-manager \
         --add-repo \
         https://download.docker.com/linux/fedora/docker-ce.repo
     dnf install -y docker-ce docker-ce-cli containerd.io && \
         break
+
+    [[ $retries -eq i ]] && { echo "Failed to install docker-ce after 5 tries"; exit 1; }
 done
-[[ $retries -eq i ]] && { echo "Failed to install docker-ce after 5 tries"; exit 1; }
 SCRIPT
diff --git a/vagrantfiles/ubuntu/master b/vagrantfiles/ubuntu/master
--- a/vagrantfiles/ubuntu/master
+++ b/vagrantfiles/ubuntu/master
@@ -13,12 +13,13 @@ else
 fi
 
 retries=5
-for ((i=0; i<retries; i++)); do
+for ((i=1; i<=retries; i++)); do
     apt-get update
     apt-get -y install screen telnet conntrack socat ${KUBERNETES_PACKAGES} && \
         break
+
+    [[ $retries -eq i ]] && { echo "Failed to install kubelet, kubeadm and other dependenices after 5 tries"; exit 1; }
 done
-[[ $retries -eq i ]] && { echo "Failed to install kubelet, kubeadm and other dependenices after 5 tries"; exit 1; }
 
 apt-mark hold kubelet kubeadm kubectl
 
diff --git a/vagrantfiles/ubuntu/pre b/vagrantfiles/ubuntu/pre
--- a/vagrantfiles/ubuntu/pre
+++ b/vagrantfiles/ubuntu/pre
@@ -1,6 +1,8 @@
 $kube_network = 'canal'
 
 $osPrepareScript = <<SCRIPT
+set -x
+
 sed -i 's/^DNS=.*/DNS=8.8.8.8 8.8.4.4/' /etc/systemd/resolved.conf
 
 sudo update-alternatives --set iptables /usr/sbin/iptables-legacy
@@ -9,11 +11,13 @@ sudo update-alternatives --set arptables /usr/sbin/arptables-legacy
 sudo update-alternatives --set ebtables /usr/sbin/ebtables-legacy
 
 retries=5
-for ((i=0; i<retries; i++)); do
+for ((i=1; i<=retries; i++)); do
     apt-get update
     apt-get -y install apt-transport-https curl software-properties-common ca-certificates && \
         break
-done
-[[ $retries -eq i ]] && { echo "Failed to install apt-transport-https and other dependenices after 5 tries"; exit 1; }
 
+    [[ $retries -eq i ]] && { echo "Failed to install apt-transport-https and other dependenices after 5 tries"; exit 1; }
+done
 SCRIPT
+
+$kubeletExtraArgsFile = '/etc/default/kubelet'
